stages:
  - build
  - test
  - cleanup

variables:
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - .gitlab-ci/pipelines/android.yml
  - .gitlab-ci/pipelines/linux.yml
  - .gitlab-ci/pipelines/windows.yml
  - .gitlab-ci/pipelines/macos.yml
  - .gitlab-ci/pipelines/ios.yml
  - .gitlab-ci/pipelines/cleanup.yml

