FROM registry.gitlab.com/equalitie/ouinet
RUN apt-get update && apt-get install -y --no-install-recommends \
      openjdk-17-jdk-headless \
      unzip \
    && rm -rf /var/lib/apt/lists/*
ENV UNZIPOPT=-q
