(use-modules (guix packages)
             (guix licenses)
             (guix build-system gnu)
             (gnu packages)
             (gnu packages autotools)
             (gnu packages base)
             (gnu packages boost)
             (gnu packages commencement)
             (gnu packages compression)
             (gnu packages cmake)
             (gnu packages texinfo)
             (gnu packages tls)
             (gnu packages libidn)
             (gnu packages libunistring)
             (gnu packages pkg-config)
             (gnu packages gnupg)
             (gnu packages version-control))

(package
  (name "ouinet")
  (version "0.0")
  (source #f)
  (build-system gnu-build-system)
  (inputs
   `(("pkg-config" ,pkg-config)
     ("autoconf" ,autoconf)
     ("automake" ,automake)
     ("cmake" , cmake)
     ("gettext" , gettext)
     ("git" , git)
     ("libgcrypt" , libgcrypt)
     ("libidn" , libidn)
     ("libressl" , libressl)
     ("libtool" , libtool)
     ("libunistring" , libunistring)
     ("patch" , patch)
     ("pkg-config" , pkg-config)
     ("gcc-toolchain" , gcc-toolchain)
     ("texinfo" , texinfo)
     ("unzip" , unzip)
     ("zlib" , zlib)
     ("boost-cxx14" , boost-cxx14)))
  (synopsis "")
  (description "")
  (home-page "https://github.com/equalitie/ouinet")
  (license expat))
