android / build-prod-image:
  stage: release
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:android - < Dockerfile.android
    - docker push $CI_REGISTRY_IMAGE:android

android / build:
  stage: build
  tags:
    - docker
  needs: ['linux / build-prod-image']
  image: registry.gitlab.com/equalitie/ouinet:android
  script:
    - mkdir -p build.android
    - cd build.android
    - ../scripts/build-android.sh
  artifacts:
    paths:
      - build.android/build-android-*/ouinet/outputs/aar/*.aar
      - build.android/build-android-*/ouinet/outputs/apk/*.apk
    expire_in: 6h

