build-image:
  stage: build-image
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker build -t $CI_REGISTRY_IMAGE:android - < Dockerfile.android
    - docker push $CI_REGISTRY_IMAGE:android

