FROM rust:slim-bookworm AS base

ENV LANG=C.UTF-8

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
      build-essential \
      cmake \
      git \
      libssl-dev \
      zlib1g-dev \
      python3-pytest \
      python3-pytest-asyncio \
      python3-pytest-timeout \
      && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/src
