FROM debian:bookworm AS base
ENV LANG=C.UTF-8

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
      build-essential \
      cmake \
      git \
      libssl-dev \
      python3-twisted \
      zlib1g-dev \
      && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/src
