include: .gitlab-ci/jobs/common/prepare-builder-image.yml

variables:
  TARGET_PLATFORM: 'android'
  BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:$TARGET_PLATFORM-builder'

android / prepare-builder-image:
  extends:
    .prepare-builder-image
  needs:
    - job: 'debian-10 / prepare-builder-image'
      optional: true

android / build:
  variables:
    TARGET_PLATFORM: 'android'
  stage: build
  tags:
    - docker
  needs:
    - job: 'android / prepare-builder-image'
      optional: true
    - job: 'debian-10 / build'
  image: $BUILDER_IMAGE
  script:
    - mkdir -p build.android
    - cd build.android
    - ../scripts/build-android.sh
  artifacts:
    paths:
      - build.android/build-android-*/ouinet/outputs/aar/*.aar
      - build.android/build-android-*/ouinet/outputs/apk/*.apk
    expire_in: 6h

# TODO: Remove this job when the build-dev-image one is stable
android / build-prod-image:
  stage: release
  tags:
    - shell
  needs:
    ['debian-10 / build-prod-image', 'android / build']
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login --password-stdin -u $CI_REGISTRY_USER $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:android - < Dockerfile.android
    - docker push $CI_REGISTRY_IMAGE:android
    - docker logout $CI_REGISTRY

