include:
  - .gitlab-ci/jobs/common/prepare-builder-image.yml

variables:
  TARGET_PLATFORM: 'android'
  BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:$TARGET_PLATFORM-builder'

android / prepare-builder-image:
  extends:
    .prepare-builder-image
  needs:
    - job: 'linux / prepare-builder-image'
      optional: true

android / build:
  variables:
    TARGET_PLATFORM: 'android'
  stage: build
  tags:
    - docker
  needs:
    - job: 'android / prepare-builder-image'
      optional: true
    - job: 'linux / build'
  image: $BUILDER_IMAGE
  script:
    - mkdir -p build.android
    - cd build.android
    - ../scripts/build-android.sh
  artifacts:
    paths:
      - build.android/build-android-*/ouinet/outputs/aar/*.aar
      - build.android/build-android-*/ouinet/outputs/apk/*.apk
    expire_in: 6h

