android / build:
  stage: build
  variables:
    BUILD_PATH: 'build'
    TARGET_OS: 'android'
  tags:
    - shell+docker
  script:
    - ./docker/linux.sh --target-os $TARGET_OS --artifact-dir $BUILD_PATH
  needs:
    - job: 'linux / build'
      optional: true
      artifacts: false
  artifacts:
    paths:
      - $BUILD_PATH/$TARGET_OS/*.aar
    expire_in: 6h
