cleanup:
  stage: cleanup
  tags:
    - shell+docker
  script:
    - docker stop ${CI_JOB_SLUG}
    - docker rmi ${CI_JOB_SLUG}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
    # allow to manually run it when the pipeline fails
    - when: manual

