include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

debian-10-boost-1.74 / build:
  variables:
    BOOST_VERSION: "1.74.0"
    TARGET_PLATFORM: 'debian-10-boost-1.74'
  extends:
    .linux-build
  needs:
    - job: 'debian-10 / prepare-builder-image'
      optional: true

debian-10-boost-1.74 / unit-test:
  variables:
    TARGET_PLATFORM: 'debian-10-boost-1.74'
  extends:
    .linux-unit-test
  needs:
    ['debian-10-boost-1.74 / build']

debian-10-boost-1.74 / integration-test:
  variables:
    TARGET_PLATFORM: 'debian-10-boost-1.74'
  extends:
    .linux-integration-test
  needs:
    ['debian-10-boost-1.74 / unit-test']