include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

debian-10 / prepare-builder-image:
  variables:
    TARGET_PLATFORM: 'debian-10'
  extends:
    .prepare-builder-image

debian-10 / build-prod-image:
  stage: release
  tags:
    - shell
  needs: ['debian-10 / integration-test']
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login --password-stdin -u $CI_REGISTRY_USER $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker logout $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true

