include:
  - .gitlab-ci/jobs/common/prepare-builder-image.yml
  - .gitlab-ci/jobs/linux.yml

debian-12-boost-1.79 / build:
  variables:
    BOOST_VERSION: "1.79.0"
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux-builder' # Reusing debian-12 image
    TARGET_PLATFORM: 'debian-12-boost-1.79'
  extends:
    .linux-build
  needs:
    - job: 'debian-12 / prepare-builder-image' # Reusing debian-12 image
      optional: true

debian-12-boost-1.79 / unit-test:
  variables:
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux-builder' # Reusing debian-12 image
    TARGET_PLATFORM: 'debian-12-boost-1.79'
  extends:
    .linux-unit-test
  needs:
    ['debian-12-boost-1.79 / build']

debian-12-boost-1.79 / integration-test:
  variables:
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux-builder' # Reusing debian-12 image
    TARGET_PLATFORM: 'debian-12-boost-1.79'
  extends:
    .linux-integration-test
  needs:
    ['debian-12-boost-1.79 / unit-test']
  before_script:
    - ln -s /usr/bin/python3 /usr/bin/python

debian-12-boost-1.79 / build-prod-image:
  stage: release
  tags:
    - shell
  needs: ['debian-12-boost-1.79 / integration-test']
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login --password-stdin -u $CI_REGISTRY_USER $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker logout $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
