include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

debian-10 / prepare-builder-image:
  variables:
    TARGET_PLATFORM: 'debian-10'
  extends:
    .prepare-builder-image

