include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

variables:
  TARGET_PLATFORM: 'debian-10'

debian-10 / prepare-builder-image:
  extends:
    .prepare-builder-image

debian-10 / build:
  extends:
    .linux-build
  needs:
    ['debian-10 / prepare-builder-image']

debian-10 / unit-test:
  extends:
    .linux-unit-test
  needs:
    ['debian-10 / build']

debian-10 / integration-test:
  extends:
    .linux-integration-test
  needs:
    ['debian-10 / build']

debian-10 / build-prod-image:
  stage: release
  tags:
    - shell
  needs: ['debian-10 / unit-test', 'debian-10 / integration-test']
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest

