include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

debian-10 / prepare-builder-image:
  variables:
    TARGET_PLATFORM: 'debian-10'
  extends:
    .prepare-builder-image

debian-10 / build:
  variables:
    TARGET_PLATFORM: 'debian-10'
  extends:
    .linux-build
  needs:
    - job: 'debian-10 / prepare-builder-image'
      optional: true

debian-10 / unit-test:
  variables:
    TARGET_PLATFORM: 'debian-10'
  extends:
    .linux-unit-test
  needs:
    ['debian-10 / build']

debian-10 / integration-test:
  variables:
    TARGET_PLATFORM: 'debian-10'
  extends:
    .linux-integration-test
  needs:
    ['debian-10 / unit-test']

debian-10 / build-prod-image:
  stage: release
  tags:
    - shell
  needs: ['debian-10 / integration-test']
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login --password-stdin -u $CI_REGISTRY_USER $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker logout $CI_REGISTRY

