include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

debian-12 / prepare-builder-image:
  variables:
    TARGET_PLATFORM: 'debian-12'
  extends:
    .prepare-builder-image

debian-12 / build:
  variables:
    TARGET_PLATFORM: 'debian-12'
  extends:
    .linux-build
  needs:
    ['debian-12 / prepare-builder-image']

debian-12 / unit-test:
  variables:
    TARGET_PLATFORM: 'debian-12'
  extends:
    .linux-unit-test
  needs:
    ['debian-12 / build']

debian-12 / integration-test:
  variables:
    TARGET_PLATFORM: 'debian-12'
  extends:
    .linux-integration-test
  needs:
    ['debian-12 / build']
  before_script:
    - ln -s /usr/bin/python3 /usr/bin/python
