include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

debian-10-boost-1.77 / build:
  variables:
    BOOST_VERSION: "1.77.0"
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:debian-10-builder' # Reusing debian-10 image
    TARGET_PLATFORM: 'debian-10-boost-1.77'
  extends:
    .linux-build
  needs:
    - job: 'debian-10 / prepare-builder-image' # Reusing debian-10 image
      optional: true

debian-10-boost-1.77 / unit-test:
  variables:
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:debian-10-builder' # Reusing debian-10 image
    TARGET_PLATFORM: 'debian-10-boost-1.77'
  extends:
    .linux-unit-test
  needs:
    ['debian-10-boost-1.77 / build']

debian-10-boost-1.77 / integration-test:
  variables:
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:debian-10-builder' # Reusing debian-10 image
    TARGET_PLATFORM: 'debian-10-boost-1.77'
  extends:
    .linux-integration-test
  needs:
    ['debian-10-boost-1.77 / unit-test']
