docker / build:
  stage: build
  tags:
    - shell+docker
  script:
    - >
      docker build --progress=plain --pull
      -t equalitie/ouinet:${CI_JOB_SLUG}
      - < Dockerfile
    - docker image rm equalitie/ouinet:${CI_JOB_SLUG}
  needs: []
  rules:
     - !reference [.optional_job, rules]
