linux / build:
  stage: build
  variables:
    BUILD_PATH: 'build'
    TARGET_OS: 'linux'
  tags:
    - shell+docker
  script:
    - ./docker/linux.sh --target-os $TARGET_OS --artifact-dir $BUILD_PATH
  artifacts:
    paths:
      - $BUILD_PATH/$TARGET_OS/client
      - $BUILD_PATH/$TARGET_OS/injector
      - $BUILD_PATH/$TARGET_OS/lib*.so*
    expire_in: 6h

linux / cpp-rust-tests:
  stage: test
  tags:
    - shell+docker
  script:
    - ./docker/linux.sh --target-os linux --run-all-tests
  needs:
    - job: 'linux / build'
      artifacts: false

linux / python-tests:
  stage: test
  tags:
    - shell+docker
  script:
    - ./docker/linux.sh --target-os linux --run-python-tests
  needs:
    - job: 'linux / test'
      artifacts: false

