variables:
  IOS_BUILD_PATH: 'build-ios/Debug-iphoneos'
  SIM_BUILD_PATH: 'build-sim/Debug-iphonesimulator'

iphoneos / build:
  stage: build
  tags:
    - macos-shell
  needs:
    - job: 'macos / build'
  artifacts:
    paths:
      - $IOS_BUILD_PATH/ouinet-ios.framework
      - $IOS_BUILD_PATH/injector.app
      - $IOS_BUILD_PATH/lib*.a
      - build.log
    expire_in: 6h
  script:
    - cd scripts
    - ./build-ios.sh clean build ios > ../build.log 2>&1

iphonesimulator / build:
  stage: build
  tags:
    - macos-shell
  needs:
    - job: 'macos / build'
  artifacts:
    paths:
      - $SIM_BUILD_PATH/ouinet-ios.framework
      - $SIM_BUILD_PATH/injector.app
      - $SIM_BUILD_PATH/lib*.a
      - build.log
    expire_in: 6h
  script:
    - cd scripts
    - ./build-ios.sh clean build sim > ../build.log 2>&1
