variables:
  IOS_BUILD_PATH: 'build.darwin/build-os64/Debug-iphoneos'
  SIM_BUILD_PATH: 'build.darwin/build-simulatorarm64/Debug-iphonesimulator'

iphoneos / build:
  stage: build
  tags:
    - macos-shell
  needs:
    - job: 'macos / build'
  artifacts:
    paths:
      - $IOS_BUILD_PATH/ouinet.framework
      - $IOS_BUILD_PATH/injector.app
      - $IOS_BUILD_PATH/lib*.a
    expire_in: 6h
  script:
    - mkdir -p build.darwin
    - cd build.darwin
    - PLATFORM=OS64 ../scripts/build-darwin.sh
  when: manual
  allow_failure: true

iphonesimulator / build:
  stage: build
  tags:
    - macos-shell
  needs:
    - job: 'macos / build'
  artifacts:
    paths:
      - $SIM_BUILD_PATH/ouinet.framework
      - $SIM_BUILD_PATH/injector.app
      - $SIM_BUILD_PATH/lib*.a
    expire_in: 6h
  script:
    - mkdir -p build.darwin
    - cd build.darwin
    - PLATFORM=SIMULATORARM64 ../scripts/build-darwin.sh
  when: manual
  allow_failure: true

combined / build:
  stage: build
  tags:
    - macos-shell
  needs:
    - job: 'iphoneos / build'
    - job: 'iphonesimulator / build'
  artifacts:
    paths:
      - build.darwin/build-combined/ouinet.xcframework
    expire_in: 6h
  script:
    - mkdir -p build.darwin
    - cd build.darwin
    - PLATFORM=COMBINED ../scripts/build-darwin.sh
  when: manual
  allow_failure: true
