include: .gitlab-ci/jobs/common/prepare-builder-image.yml
include: .gitlab-ci/jobs/linux.yml

variables:
  TARGET_PLATFORM: 'linux'

linux / prepare-builder-image:
  extends:
    .prepare-builder-image

linux / build:
  extends:
    .linux-build
  needs:
    ['linux / prepare-builder-image']

linux / unit-test:
  extends:
    .linux-unit-test
  needs:
    ['linux / build']

linux / integration-test:
  extends:
    .linux-integration-test
  needs:
    ['linux / build']

linux / build-prod-image:
  stage: release
  tags:
    - shell
  needs: ['linux / unit-test', 'linux / integration-test']
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest

