linux / build:
  stage: build
  tags:
    - shell+docker
  variables:
    BUILD_PATH: 'build'
    TARGET_OS: 'linux'
    CMAKE_BUILD_TYPE: 'Release'
  script:
    - >
      ./docker/linux.sh
      --target-os $TARGET_OS
      --artifact-dir $BUILD_PATH
      --cmake-build-type $CMAKE_BUILD_TYPE
      $CONTAINER_ARGS
  artifacts:
    paths:
      - $BUILD_PATH/$TARGET_OS/client
      - $BUILD_PATH/$TARGET_OS/injector
      - $BUILD_PATH/$TARGET_OS/lib*.so*
    expire_in: 6h
  rules:
     - !reference [.required_job, rules]

linux / cpp-rust-tests:
  stage: test
  tags:
    - shell+docker
  timeout: 30 minutes
  script:
    - >
      ./docker/linux.sh
      --target-os linux
      --run-cpp-rust-tests
      --exclude-test test_fetch
      --exclude-test test_i2p
      --exclude-test test_i2p_fetch
      --exclude-test test_i2p_tracker
      $CONTAINER_ARGS
  needs:
    - job: 'linux / build'
      artifacts: false
  rules:
    - !reference [.required_job, rules]

linux / python-tests:
  stage: test
  timeout: 30 minutes
  tags:
    - shell+docker
  script:
    - >
      ./docker/linux.sh
      --target-os linux
      --run-python-tests
      $CONTAINER_ARGS
  needs:
    - job: 'linux / cpp-rust-tests'
      artifacts: false
  rules:
     - !reference [.optional_job, rules]
