include:
  - .gitlab-ci/jobs/common/prepare-builder-image.yml
  - .gitlab-ci/jobs/linux.yml

variables:
  TARGET_PLATFORM: 'linux'
  BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux'

linux / prepare-builder-image:
  extends:
    .prepare-builder-image

linux / build:
  variables:
    BOOST_VERSION: "1.87.0"
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux-builder'
  extends:
    .linux-build
  needs:
    - job: 'linux / prepare-builder-image'
      optional: true

linux / unit-test:
  variables:
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux-builder'
  extends:
    .linux-unit-test
  needs:
    ['linux / build']

linux / integration-test:
  variables:
    BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:linux-builder'
  extends:
    .linux-integration-test
  needs:
    ['linux / unit-test']
  before_script:
    - ln -s /usr/bin/python3 /usr/bin/python

