include:
  - .gitlab-ci/jobs/linux.yml

variables:
  TARGET_PLATFORM: 'linux'

linux / build:
  extends:
    .linux-build

linux / benchmark:
  extends:
    .linux-benchmark
  needs:
    ['linux / build']
