include:
  - .gitlab-ci/jobs/common/prepare-macos-image.yml

variables:
  BUILD_PATH: 'build.darwin/build-mac_arm64/Debug'
  BOOST_PATH: 'build.darwin/build-mac_arm64/boost/src/built_boost'
  GCRYPT_PATH: 'build.darwin/build-mac_arm64/gcrypt'
  GPGERROR_PATH: 'build.darwin/build-mac_arm64/gpg_error'
  TESTS_PATH: 'build.darwin/build-mac_arm64/test/Debug'
  HOMEBREW_NO_AUTO_UPDATE: 1

macos / build:
  stage: build
  extends:
    - .prepare-macos-image
  artifacts:
    paths:
      - $BUILD_PATH/client.app
      - $BUILD_PATH/injector.app
      - $BUILD_PATH/lib*.dylib
      - $BUILD_PATH/lib*.a
      - $BOOST_PATH/b2
      - $GCRYPT_PATH/src/gcrypt/cipher/gost-s-box
      - $GCRYPT_PATH/out/lib/lib*.dylib
      - $GPGERROR_PATH/out/lib/lib*.dylib
      - $GPGERROR_PATH/src/gpg_error/src/mkerrcodes
      - $GPGERROR_PATH/src/gpg_error/src/mkheader
      - $TESTS_PATH/bt-*
      - $TESTS_PATH/test-*
      - build.darwin/xcodebuild.log
    expire_in: 6h
  script:
    - mkdir -p build.darwin
    - cd build.darwin
    - PLATFORM=MAC_ARM64 ../scripts/build-darwin.sh | tee xcodebuild.log | xcpretty
  allow_failure: true

macos / unit-test:
  stage: test
  extends:
    - .prepare-macos-image
  artifacts:
    paths:
      - $BUILD_PATH/client.app
      - $BUILD_PATH/injector.app
      - $BUILD_PATH/lib*.dylib
      - $BUILD_PATH/lib*.a
      - $GCRYPT_PATH/out/lib/lib*.dylib
      - $GPGERROR_PATH/out/lib/lib*.dylib
      - $TESTS_PATH/test-*
    expire_in: 6h
  script:
    - export LD_LIBRARY_PATH=$CI_PROJECT_DIR/$BUILD_PATH:/usr/local/lib
    - for test in ./$TESTS_PATH/test*.app/Contents/MacOS/test*; do "$test" --log_level=test_suite; done
  allow_failure: true
  needs:
    ['macos / build']
