windows / build:
  stage: build
  tags:
    - shell+docker
  variables:
    BUILD_PATH: 'build'
    TARGET_OS: 'windows'
    CMAKE_BUILD_TYPE: 'Release'
  script:
    - >
      ./docker/linux.sh
      --target-os $TARGET_OS
      --artifact-dir $BUILD_PATH
      --cmake-build-type $CMAKE_BUILD_TYPE
      $CONTAINER_ARGS
  artifacts:
    paths:
      - $BUILD_PATH/$TARGET_OS/client.exe
      - $BUILD_PATH/$TARGET_OS/injector.exe
      - $BUILD_PATH/$TARGET_OS/lib*.dll*
    expire_in: 6h
  rules:
     - !reference [.optional_job, rules]

windows / cpp-rust-tests:
  stage: test
  tags:
    - shell+docker
  timeout: 30 minutes
  script:
    - >
      ./docker/linux.sh
      --target-os windows
      --run-all-tests
      --exclude-test test_fetch
      --exclude-test test_http_store
      --exclude-test test_i2p
      --exclude-test test_i2p_fetch
      --exclude-test test_i2p_tracker
      $CONTAINER_ARGS
  needs:
    - job: 'windows / build'
      artifacts: false
  rules:
     - !reference [.optional_job, rules]

