variables:
  TARGET_PLATFORM: 'windows'
  BUILDER_IMAGE_TAG: '${TARGET_PLATFORM}-builder'
  BUILDER_IMAGE: '${CI_REGISTRY_IMAGE}:${BUILDER_IMAGE_TAG}'

windows / prepare-builder-image:
  stage: prepare
  tags:
    - windows-shell
  needs:
    - job: 'debian-12 / prepare-builder-image'
      optional: true
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - Get-Content docker/Dockerfile.${BUILDER_IMAGE_TAG} | docker build --pull -t ${BUILDER_IMAGE} -
    - docker push ${BUILDER_IMAGE}
    - docker logout ${CI_REGISTRY}

windows / build:
  stage: build
  tags:
    - windows-docker
  needs:
    - job: 'windows / prepare-builder-image'
      optional: true
  image: $BUILDER_IMAGE
  script:
    - mkdir -p build.windows
    - cd build.windows
    - bash ${CI_PROJECT_DIR}/scripts/build-windows.sh
