include: .gitlab-ci/jobs/common/prepare-builder-image.yml

variables:
  TARGET_PLATFORM: 'windows'
  BUILDER_IMAGE: '$CI_REGISTRY_IMAGE:$TARGET_PLATFORM-builder'

windows / prepare-builder-image:
  extends:
    .prepare-builder-image
  needs:
    - job: 'debian-12 / prepare-builder-image'
      optional: true

