.prepare-builder-image:
  stage: prepare
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_TAG - < docker/Dockerfile.$CI_REGISTRY_IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_TAG

